### ISSUE TITLE
My Dock Finder Icon to original Apple icon

### ISSUE THREAD

**Issue by Amritesh92** [Runixe786/Macified-Windows#1]
Please provide the original apple icon in the mydock finder.

**Comment by Runixe786** [comment]
It's not possible by my side as I can only provide backup file which won't include custom icon packs/styles but only the icon placement , size etc

But here's one thing you can do, first open the app you want in dock, right click on app icon in dock and select "keep in dock" 

Now search for its original icon on Google, download it and now edit that app icon by right clicking again> edit the icon

Select that downloaded icon and apply. Remember to uncheck and check back the option of "set to macOS standards"

**Comment by Runixe786** [comment]
> Please provide the original apple icon in the mydock finder. 

It's not possible by my side as I can only provide backup file which won't include custom icon packs/styles but only the icon placement , size etc

But here's one thing you can do, first open the app you want in dock, right click on app icon in dock and select "keep in dock"

Now search for its original icon on Google, download it and now edit that app icon by right clicking again> edit the icon

Select that downloaded icon and apply. Remember to uncheck and check back the option of "set to macOS standards"

I did the same for some apps I want in dock while others already have their original icon. So you might have seen blank icon or question mark icon when you imported the backup. Those were the apps for which I have set custom icons.

**Comment by Amritesh92** [comment]
Sorry but i am not talking about the lower dock area, instead i am asking
about the top of the screen finder button which is currently just a circle,
i want to change that to an Apple logo.. as it is in the original macos...
And yeah i am so in love with this, that i have shared your github repo of
"Macified Windows" on many places loke "Hackintosh" subreddit. Keep up the
good work. 👍

**Comment by Runixe786** [comment]
oh that, its actually left to be written as you can see "extra customisations" segment is be to updated. but there is already a file of apple icon inside dock_macifiedwindows>themes folder . go to preferences>myfinder settings>look and behavior and there will be a drop-down button of "myfinder menu icon" . from there select that applelogo.png and you are done :)

thanks for your contribution by sharing, i appreciate it.

**Comment by Amritesh92** [comment]
Oh thanks with the Apple Logo it looks much more better now, please provide
customisation for the lock screen as that is the only thing not looking
good.
Here is the link of my reddit post -
https://www.reddit.com/r/hackintosh/s/M5IWMYr9RA

**Comment by Runixe786** [comment]
working on it, but since windows dont allow you to change default lock screen, i am making a rainmeter skin which will work as a screensaver (since i dont know how to implement screen lock in a skin) and here is the first look: https://t.me/GithubGeeks/14

will be dropping beta version of this soon. 
and closing this issue now.

**Comment by Amritesh92** [comment]
Oh that looks promising, keep up the good work and spread the update fast!!
