### ISSUE TITLE
showing warning it can harm your system 

### ISSUE THREAD

**Issue by anix2040** [Runixe786/Macified-Windows#4]
![Screenshot (1477)](https://github.com/Runixe786/Macified-Windows/assets/121334995/6b2f6913-5c43-4c4c-9fa5-76c3f18e64ec)
   
please help

**Comment by Runixe786** [comment]
seems like you never installed a custom theme before. you can ignore the warning, i havent seen any problems using it on my all laptops.

**Comment by anix2040** [comment]
thanks , can you please tell me how to revert to the original theme back ?
